# Testing this with:
# Set QUAY_USER and QUAY_PASSWORD to your credentials
# Set OC_PROJECT to the name of the namespace to be used. eg. OC_PROJECT=idmocp-52
# Build the image and publish by:
# # sudo podman image prune --force && sudo podman build --squash --isolation chroot -t quay.io/avisied0/freeipa-openshift-container:dev-test -f Dockerfile.centos-8 . && sudo podman push --creds $QUAY_USER:$QUAY_PASSWORD quay.io/$QUAY_USER/freeipa-openshift-container:dev-test
# Select the project:
# # oc project $OC_PROJECT || oc new-project $OC_PROJECT
# Deploy the system by:
# # oc delete all,secret --selector app=freeipa; oc apply -f pod.yaml
# Get information about the pod
# # oc describe pod/freeipa-master
# See the init container log by:
# # oc logs -f freeipa-master -c freeipa-master-init

# Pipeline job used as reference: https://travis-ci.org/github/avisiedo/freeipa-openshift-container/jobs/721264298
---
kind: Secret
apiVersion: v1
metadata:
  # name: "${IPA_SERVER_SERVICE}-password"
  name: "freeipa-password"
  labels:
    app: freeipa
stringData:
  # admin.password: "${IPA_ADMIN_PASSWORD}"
  admin.password: "administrator"
---
# kind: ServiceAccount
# apiVersion: v1
# metadata:
#   name: "freeipa-sa"
#   labels:
#     app: freeipa
# spec:
# ---
kind: Service
apiVersion: v1
metadata:
  name: freeipa-svc
  labels:
    app: freeipa
spec:
  type: ExternalName
  externalName: freeipa-master.apps.permanent.idmocp.idm.lab.bos.redhat.com
  # publishNotReadyAddresses: true
  selector:
    app: freeipa
    role: master
  # 1. You must make sure these network ports are open:
  # TCP Ports:
  #   * 80, 443: HTTP/HTTPS
  #   * 389, 636: LDAP/LDAPS
  #   * 88, 464: kerberos
  #   * 53: bind
  # UDP Ports:
  #   * 88, 464: kerberos
  #   * 53: bind
  ports:
    - name: http-tcp
      port: 80
      protocol: TCP
    - name: https-tcp
      port: 443
      protocol: TCP
    - name: ldap-tcp
      port: 389
      protocol: TCP
    - name: ldaps-tcp
      port: 636
      protocol: TCP

    - name: kerberos-tcp
      port: 88
      protocol: TCP
    - name: kerberos-udp
      port: 88
      protocol: UDP
    - name: kpasswd-tcp
      port: 464
      protocol: TCP
    - name: kpasswd-udp
      port: 464
      protocol: UDP

    - name: dns-tcp
      port: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      protocol: UDP
---
kind: Route
apiVersion: v1
metadata:
  name: freeipa-route
  labels:
    app: freeipa
spec:
  host: freeipa-master.apps.permanent.idmocp.idm.lab.bos.redhat.com
  to:
    kind: Service
    name: freeipa-svc
---
# kind: ImageStream
# apiVersion: v1
# metadata:
#   app: freeipa
#   name: freeipa-imagestream
# spec:
#   lookupPolicy:
#     local: false
#   tags:
#     - name: freeipa-master
#       from: quay.io/avisied0/freeipa-openshift-container:dev-test
# ---
kind: Pod
apiVersion: v1
metadata:
  name: freeipa-master
  # annotations: {}
  # labels:
  #   deployment: freeipa-master
  #   deploymentconfig: freeipa
  # generateName: freeipa-master-
  labels:
    app: freeipa
    role: master
spec:
  # https://kubernetes.io/docs/tasks/debug-application-cluster/debug-init-containers/
  initContainers:
    # - image: docker.io/freeipa/freeipa-server:fedora-32
    - image: quay.io/avisied0/freeipa-openshift-container:dev-test
      imagePullPolicy: Always
      name: freeipa-master-init
      env:
        - name: DEBUG_TRACE
          value: "1"
        - name: INIT_WRAPPER
          value: "1"
        - name: IPA_SERVER_HOSTNAME
          value: "freeipa-master.apps.permanent.idmocp.idm.lab.bos.redhat.com"
        - name: SYSTEMD_LOG_LEVEL
          value: "debug"
        - name: SYSTEMD_LOG_TARGET
          value: "journal+console"
        - name: SYSTEMD_LOG_COLOR
          value: "no"
        # Review this one
        # - name: IPA_SERVER_IP
        #   value: "${IPA_SERVER_IP}"
        # Review this one
        # - name: IPA_SERVER_INSTALL_OPTS
        #   value: "${IPA_SERVER_INSTALL_OPTS}"
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: "freeipa-password"
              key: admin.password
      # command: ipa-server-install --no-host-dns --mkhomedir
      command: ["/usr/sbin/init", "--no-pager"]
      volumeMounts:
        - mountPath: /data
          name: freeipa-data
  hostname: freeipa-master
  containers:
    - image: "quay.io/avisied0/freeipa-openshift-container:dev-test"
      # imagePullPolicy: IfNotPresent
      imagePullPolicy: Always
      name: freeipa
      ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        - containerPort: 80
          protocol: TCP
        - containerPort: 88
          protocol: TCP
        - containerPort: 88
          protocol: UDP
        - containerPort: 123
          protocol: UDP
        - containerPort: 389
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        - containerPort: 464
          protocol: TCP
        - containerPort: 464
          protocol: UDP
        - containerPort: 636
          protocol: TCP
      env:
        - name: DEBUG_TRACE
          value: "1"
        - name: IPA_SERVER_HOSTNAME
          value: "freeipa-master"
      #   - name: IPA_SERVER_HOSTNAME
      #     value: "freeipa-master"
      #   # Review this one
      #   - name: IPA_SERVER_IP
      #     value: "${IPA_SERVER_IP}"
      #   # Review this one
      #   - name: IPA_SERVER_INSTALL_OPTS
      #     value: "${IPA_SERVER_INSTALL_OPTS}"
      #   - name: PASSWORD
      #     valueFrom:
      #       secretKeyRef:
      #         name: "freeipa-password"
      #         key: admin.password
      command: ["/usr/sbin/init"]
      resources: {}
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /data
          name: freeipa-data
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token
          readOnly: true
  volumes:
    - name: freeipa-data
      emptyDir: {}
    - name: default-token
      projected:
        sources:
          - serviceAccountToken:
              path: serviceaccount
              expirationSeconds: 7200
      

  # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config
  dnsPolicy: "Default"
