---
kind: Secret
apiVersion: v1
metadata:
  # name: "${IPA_SERVER_SERVICE}-password"
  name: "freeipa-password"
stringData:
  # admin.password: "${IPA_ADMIN_PASSWORD}"
  admin.password: "administrator"
# ---
# kind: ServiceAccount
# apiVersion: v1
# metadata:
#   name: "freeipa-sa"
# spec:
  
---
kind: Pod
apiVersion: v1
metadata:
  name: freeipa-master
  # annotations: {}
  # labels:
  #   deployment: freeipa-master
  #   deploymentconfig: freeipa
  # generateName: freeipa-master-
spec:
  # https://kubernetes.io/docs/tasks/debug-application-cluster/debug-init-containers/
  initContainers:
    # - image: docker.io/freeipa/freeipa-server:fedora-32
    - image: quay.io/avisied0/freeipa-openshift-container:dev-test
      imagePullPolicy: Always
      name: freeipa-master-init
      env:
        - name: DEBUG_TRACE
          value: "1"
        - name: INIT_WRAPPER
          value: "1"
        - name: IPA_SERVER_HOSTNAME
          value: "freeipa-master"
        # Review this one
        - name: IPA_SERVER_IP
          value: "${IPA_SERVER_IP}"
        # Review this one
        - name: IPA_SERVER_INSTALL_OPTS
          value: "${IPA_SERVER_INSTALL_OPTS}"
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: "freeipa-password"
              key: admin.password
      # command: ipa-server-install --no-host-dns --mkhomedir
      command: ["/usr/sbin/init"]
      volumeMounts:
        - mountPath: /data
          name: freeipa-data
  hostname: freeipa-master
  containers:
    - image: "quay.io/avisied0/freeipa-openshift-container:dev-test"
      # imagePullPolicy: IfNotPresent
      imagePullPolicy: Always
      name: freeipa
      ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        - containerPort: 80
          protocol: TCP
        - containerPort: 88
          protocol: TCP
        - containerPort: 88
          protocol: UDP
        - containerPort: 123
          protocol: UDP
        - containerPort: 389
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        - containerPort: 464
          protocol: TCP
        - containerPort: 464
          protocol: UDP
        - containerPort: 636
          protocol: TCP
      env:
        - name: DEBUG_TRACE
          value: "1"
        - name: IPA_SERVER_HOSTNAME
          value: "freeipa-master"
      #   - name: IPA_SERVER_HOSTNAME
      #     value: "freeipa-master"
      #   # Review this one
      #   - name: IPA_SERVER_IP
      #     value: "${IPA_SERVER_IP}"
      #   # Review this one
      #   - name: IPA_SERVER_INSTALL_OPTS
      #     value: "${IPA_SERVER_INSTALL_OPTS}"
      #   - name: PASSWORD
      #     valueFrom:
      #       secretKeyRef:
      #         name: "freeipa-password"
      #         key: admin.password
      command: ["/usr/sbin/init"]
      resources: {}
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /data
          name: freeipa-data
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token
          readOnly: true
  volumes:
    - name: freeipa-data
      emptyDir: {}
    - name: default-token
      projected:
        sources:
          - serviceAccountToken:
              path: serviceaccount
              expirationSeconds: 7200
      

  # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config
  dnsPolicy: "Default"


  


